apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-alpine
  namespace: vulnerable-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: old-alpine
  template:
    metadata:
      labels:
        app: old-alpine
    spec:
      containers:
      - name: alpine
        image: alpine:3.10
        command: ["sleep", "infinity"]
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi