operator:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

trivy:
  ignoreUnfixed: false
  severity: "CRITICAL,HIGH,MEDIUM,LOW"
  timeout: "5m0s"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1
      memory: 1Gi

trivyOperator:
  scanJobTimeout: "5m"
  scanJobsConcurrentLimit: 2
  vulnerabilityReportsPlugin: "Trivy"
  compressLogs: true

serviceAccount:
  create: false  # We create it in Terraform
  name: trivy-operator