name: Deploy K8s

on:
  push:
    branches: [main]
    paths:
          - 'k8s/**'
          - '.github/workflows/k8s-deploy.yml'
    workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/get-gke-credentials@v2   # ← bump to v2
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: us-central1

      - name: Deploy namespaces
        run: |
          kubectl apply -f k8s/namespaces/
          kubectl wait --for=jsonpath='{.status.phase}'=Active \
            namespace/apt-simulation \
            namespace/vulnerable-apps \
            namespace/security-monitoring \
            --timeout=30s

      - name: Deploy vulnerable apps
        run: kubectl apply -f k8s/vulnerable-apps/ --force   # ← add --force

      - name: Deploy apt simulation
        run: kubectl apply -f k8s/apt-simulation/ --force    # ← add --force