name: Terraform Apply

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        env:
          TF_LOG: INFO
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_LOG: INFO
          TF_LOG_PATH: terraform.log    # ← write logs to file
        run: |
          terraform apply -auto-approve \
            --lock=false \
            -refresh=false              # ← skip refresh if infra hasn't changed

      - name: Show Terraform logs on failure
        if: failure()
        run: tail -100 terraform/terraform.log